<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxMap_TwigComponent_MapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux_map.twig_component.map' service.
     *
     * @return \Symfony\UX\Map\Twig\UXMapComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-map/src/Twig/UXMapComponent.php';

        $container->factories['service_container']['.ux_map.twig_component.map'] = function ($container) {
            return new \Symfony\UX\Map\Twig\UXMapComponent();
        };

        return $container->factories['service_container']['.ux_map.twig_component.map']($container);
    }
}
