<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationIconCompilerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpomkyLabs\PwaBundle\Service\ApplicationIconCompiler' shared autowired service.
     *
     * @return \SpomkyLabs\PwaBundle\Service\ApplicationIconCompiler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/Service/ApplicationIconCompiler.php';

        return $container->privates['SpomkyLabs\\PwaBundle\\Service\\ApplicationIconCompiler'] = new \SpomkyLabs\PwaBundle\Service\ApplicationIconCompiler(($container->privates['SpomkyLabs\\PwaBundle\\Service\\IconResolver'] ?? self::getIconResolverService($container)), ($container->privates['SpomkyLabs\\PwaBundle\\Dto\\Manifest'] ?? self::getManifestService($container)), true);
    }
}
