<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuilderRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Endroid\QrCode\Builder\BuilderRegistry' shared autowired service.
     *
     * @return \Endroid\QrCode\Builder\BuilderRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/BuilderRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/BuilderRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/BuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/Builder.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Writer/WriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Writer/ValidatingWriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Writer/AbstractGdWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Writer/WebPWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Encoding/EncodingInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Encoding/Encoding.php';

        $container->privates['Endroid\\QrCode\\Builder\\BuilderRegistry'] = $instance = new \Endroid\QrCode\Builder\BuilderRegistry();

        $instance->set('default', new \Endroid\QrCode\Builder\Builder(new \Endroid\QrCode\Writer\WebPWriter(), [], false, '', new \Endroid\QrCode\Encoding\Encoding('UTF-8'), \Endroid\QrCode\ErrorCorrectionLevel::Low, 300, 10, \Endroid\QrCode\RoundBlockSizeMode::Margin));

        return $instance;
    }
}
