<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateIconsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpomkyLabs\PwaBundle\Command\CreateIconsCommand' shared autowired service.
     *
     * @return \SpomkyLabs\PwaBundle\Command\CreateIconsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/Command/CreateIconsCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->privates['SpomkyLabs\\PwaBundle\\Command\\CreateIconsCommand'] = $instance = new \SpomkyLabs\PwaBundle\Command\CreateIconsCommand(($container->privates['asset_mapper'] ?? self::getAssetMapperService($container)), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), \dirname(__DIR__, 4), ($container->privates['SpomkyLabs\\PwaBundle\\ImageProcessor\\ImagickImageProcessor'] ??= new \SpomkyLabs\PwaBundle\ImageProcessor\ImagickImageProcessor()));

        $instance->setName('pwa:create:icons');
        $instance->setDescription('[DEPRECATED] Generate icons for your PWA');

        return $instance;
    }
}
