<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateScreenshotCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpomkyLabs\PwaBundle\Command\CreateScreenshotCommand' shared autowired service.
     *
     * @return \SpomkyLabs\PwaBundle\Command\CreateScreenshotCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/Command/CreateScreenshotCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->privates['SpomkyLabs\\PwaBundle\\Command\\CreateScreenshotCommand'] = $instance = new \SpomkyLabs\PwaBundle\Command\CreateScreenshotCommand(($container->privates['asset_mapper'] ?? self::getAssetMapperService($container)), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), \dirname(__DIR__, 4), ($container->privates['SpomkyLabs\\PwaBundle\\ImageProcessor\\ImagickImageProcessor'] ??= new \SpomkyLabs\PwaBundle\ImageProcessor\ImagickImageProcessor()), NULL, NULL);

        $instance->setName('pwa:create:screenshot');
        $instance->setDescription('[DEPRECATED] Take a screenshot of the application store it in your asset folder');

        return $instance;
    }
}
