<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDokkuConfigCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Survos\DeploymentBundle\Command\DokkuConfigCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Survos\\DeploymentBundle\\Command\\DokkuConfigCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('dokku:config', [], 'Configure a project for deployment on dukku', false, #[\Closure(name: 'Survos\\DeploymentBundle\\Command\\DokkuConfigCommand')] fn (): \Survos\DeploymentBundle\Command\DokkuConfigCommand => ($container->privates['Survos\\DeploymentBundle\\Command\\DokkuConfigCommand'] ?? $container->load('getDokkuConfigCommandService')));
    }
}
