<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDokkuConfigCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Survos\DeploymentBundle\Command\DokkuConfigCommand' shared autowired service.
     *
     * @return \Survos\DeploymentBundle\Command\DokkuConfigCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/ConfigureWithAttributes.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/Invokable.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/InvokableCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/InvokableServiceCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/RunsCommands.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/console-extra/src/RunsProcesses.php';
        include_once \dirname(__DIR__, 4).'/vendor/survos/deployment-bundle/src/Command/DokkuConfigCommand.php';

        $container->privates['Survos\\DeploymentBundle\\Command\\DokkuConfigCommand'] = $instance = new \Survos\DeploymentBundle\Command\DokkuConfigCommand(\dirname(__DIR__, 4));

        $instance->setInvokeContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBagInterface' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBagInterface' => '?',
        ]))->withContext('Survos\\DeploymentBundle\\Command\\DokkuConfigCommand', $container));
        $instance->setName('dokku:config');
        $instance->setDescription('Configure a project for deployment on dukku');

        return $instance;
    }
}
