<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontCacheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpomkyLabs\PwaBundle\CachingStrategy\FontCache' shared autowired service.
     *
     * @return \SpomkyLabs\PwaBundle\CachingStrategy\FontCache
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/CachingStrategy/HasCacheStrategiesInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/CachingStrategy/FontCache.php';

        return $container->privates['SpomkyLabs\\PwaBundle\\CachingStrategy\\FontCache'] = new \SpomkyLabs\PwaBundle\CachingStrategy\FontCache(($container->privates['SpomkyLabs\\PwaBundle\\Dto\\ServiceWorker'] ?? self::getServiceWorkerService($container)), ($container->privates['asset_mapper'] ?? self::getAssetMapperService($container)), ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)), true);
    }
}
