<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInspectorTestCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Inspector\Symfony\Bundle\Command\InspectorTestCommand' shared service.
     *
     * @return \Inspector\Symfony\Bundle\Command\InspectorTestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/inspector-apm/inspector-symfony/src/Command/InspectorTestCommand.php';

        $a = new \Inspector\Configuration($container->getEnv('INSPECTOR_INGESTION_KEY'));
        $a->setEnabled(true);
        $a->setUrl('https://ingest.inspector.dev');
        $a->setTransport('async');
        $a->setVersion('1.8.2');

        $container->privates['Inspector\\Symfony\\Bundle\\Command\\InspectorTestCommand'] = $instance = new \Inspector\Symfony\Bundle\Command\InspectorTestCommand(($container->services['Inspector\\Inspector'] ?? self::getInspectorService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $a);

        $instance->setName('inspector:test');

        return $instance;
    }
}
