<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncrementCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Bizkit\VersioningBundle\Command\IncrementCommand' shared service.
     *
     * @return \Bizkit\VersioningBundle\Command\IncrementCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Command/IncrementCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Reader/ReaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Reader/AbstractFileReader.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Reader/YamlFileReader.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Writer/WriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Writer/AbstractFileWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Writer/YamlFileWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Strategy/StrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/Strategy/SemVerStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/VCS/VCSHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/bizkit/versioning-bundle/src/VCS/GitHandler.php';

        $container->privates['Bizkit\\VersioningBundle\\Command\\IncrementCommand'] = $instance = new \Bizkit\VersioningBundle\Command\IncrementCommand((\dirname(__DIR__, 4).'/config/version.yaml'), new \Bizkit\VersioningBundle\Reader\YamlFileReader((\dirname(__DIR__, 4).'/config/version.yaml'), 'application'), new \Bizkit\VersioningBundle\Writer\YamlFileWriter((\dirname(__DIR__, 4).'/config/version.yaml'), 'application'), new \Bizkit\VersioningBundle\Strategy\SemVerStrategy('minor'), new \Bizkit\VersioningBundle\VCS\GitHandler((\dirname(__DIR__, 4).'/config/version.yaml'), 'Update application version to %s', 'Update application version to %s', NULL, NULL, NULL), 'ask');

        $instance->setName('bizkit:versioning:increment');
        $instance->setDescription('Increments the version using the configured versioning strategy.');

        return $instance;
    }
}
