<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncrementCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Bizkit\VersioningBundle\Command\IncrementCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Bizkit\\VersioningBundle\\Command\\IncrementCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('bizkit:versioning:increment', [], 'Increments the version using the configured versioning strategy.', false, #[\Closure(name: 'Bizkit\\VersioningBundle\\Command\\IncrementCommand')] fn (): \Bizkit\VersioningBundle\Command\IncrementCommand => ($container->privates['Bizkit\\VersioningBundle\\Command\\IncrementCommand'] ?? $container->load('getIncrementCommandService')));
    }
}
