<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_Twig_RuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'knp_menu.twig.runtime' shared service.
     *
     * @return \Knp\Menu\Twig\MenuRuntimeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Twig/MenuRuntimeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Util/MenuManipulator.php';

        $a = ($container->privates['knp_menu.helper'] ?? $container->load('getKnpMenu_HelperService'));

        if (isset($container->privates['knp_menu.twig.runtime'])) {
            return $container->privates['knp_menu.twig.runtime'];
        }

        return $container->privates['knp_menu.twig.runtime'] = new \Knp\Menu\Twig\MenuRuntimeExtension($a, ($container->services['knp_menu.matcher'] ?? $container->load('getKnpMenu_MatcherService')), ($container->privates['knp_menu.manipulator'] ??= new \Knp\Menu\Util\MenuManipulator()));
    }
}
