<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListCacheStrategiesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.SpomkyLabs\PwaBundle\Command\ListCacheStrategiesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.SpomkyLabs\\PwaBundle\\Command\\ListCacheStrategiesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pwa:cache:list-strategies', [], 'List the available cache strategies', false, #[\Closure(name: 'SpomkyLabs\\PwaBundle\\Command\\ListCacheStrategiesCommand')] fn (): \SpomkyLabs\PwaBundle\Command\ListCacheStrategiesCommand => ($container->privates['SpomkyLabs\\PwaBundle\\Command\\ListCacheStrategiesCommand'] ?? $container->load('getListCacheStrategiesCommandService')));
    }
}
