<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPwaRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpomkyLabs\PwaBundle\Twig\PwaRuntime' shared autowired service.
     *
     * @return \SpomkyLabs\PwaBundle\Twig\PwaRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/Twig/PwaRuntime.php';

        return $container->privates['SpomkyLabs\\PwaBundle\\Twig\\PwaRuntime'] = new \SpomkyLabs\PwaBundle\Twig\PwaRuntime(($container->privates['asset_mapper'] ?? self::getAssetMapperService($container)), ($container->privates['SpomkyLabs\\PwaBundle\\Dto\\Manifest'] ?? self::getManifestService($container)), ($container->privates['SpomkyLabs\\PwaBundle\\Dto\\Favicons'] ?? self::getFaviconsService($container)), ($container->privates['SpomkyLabs\\PwaBundle\\Service\\FaviconsCompiler'] ?? self::getFaviconsCompilerService($container)), '/pwa/site.{locale}.webmanifest', ($container->privates['nelmio_security.csp_listener'] ?? self::getNelmioSecurity_CspListenerService($container)));
    }
}
