<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouteMatchCallbackHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpomkyLabs\PwaBundle\MatchCallbackHandler\RouteMatchCallbackHandler' shared autowired service.
     *
     * @return \SpomkyLabs\PwaBundle\MatchCallbackHandler\RouteMatchCallbackHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/MatchCallbackHandler/MatchCallbackHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/MatchCallbackHandler/RouteMatchCallbackHandler.php';

        return $container->privates['SpomkyLabs\\PwaBundle\\MatchCallbackHandler\\RouteMatchCallbackHandler'] = new \SpomkyLabs\PwaBundle\MatchCallbackHandler\RouteMatchCallbackHandler(($container->services['router'] ?? self::getRouterService($container)));
    }
}
