<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_factory' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentTemplateFinderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentTemplateFinder.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }

        return $container->privates['ux.twig_component.component_factory'] = new \Symfony\UX\TwigComponent\ComponentFactory(new \Symfony\UX\TwigComponent\ComponentTemplateFinder(($container->privates['twig.loader.native_filesystem'] ?? self::getTwig_Loader_NativeFilesystemService($container)), 'components/'), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Geolocation' => [false, 'App\\Twig\\Component\\Geolocation', 'getGeolocationService', true],
            'UX:Icon' => [false, '.ux_icons.twig_component.icon', 'get_UxIcons_TwigComponent_IconService', true],
            'UX:Map' => [false, '.ux_map.twig_component.map', 'get_UxMap_TwigComponent_MapService', true],
            'mobile_menu' => [false, 'Survos\\FwBundle\\Components\\MenuComponent', 'getMenuComponentService', true],
        ], [
            'Geolocation' => '?',
            'UX:Icon' => '?',
            'UX:Map' => '?',
            'mobile_menu' => '?',
        ]), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), $a, ['Geolocation' => ['key' => 'Geolocation', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'route' => 'ux_live_component', 'method' => 'post', 'url_reference_type' => 1, 'service_id' => 'App\\Twig\\Component\\Geolocation', 'class' => 'App\\Twig\\Component\\Geolocation', 'template' => 'components/Geolocation.html.twig', 'pre_mount' => [], 'mount' => [], 'post_mount' => []], 'UX:Icon' => ['key' => 'UX:Icon', 'service_id' => '.ux_icons.twig_component.icon', 'class' => 'Symfony\\UX\\Icons\\Twig\\UXIconComponent', 'template' => 'components/UX/Icon.html.twig', 'pre_mount' => [], 'mount' => [], 'post_mount' => []], 'UX:Map' => ['key' => 'UX:Map', 'service_id' => '.ux_map.twig_component.map', 'class' => 'Symfony\\UX\\Map\\Twig\\UXMapComponent', 'template' => 'components/UX/Map.html.twig', 'pre_mount' => [], 'mount' => [], 'post_mount' => []], 'mobile_menu' => ['key' => 'mobile_menu', 'template' => '@SurvosFw/components/menu.html.twig', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'service_id' => 'Survos\\FwBundle\\Components\\MenuComponent', 'class' => 'Survos\\FwBundle\\Components\\MenuComponent', 'pre_mount' => [], 'mount' => ['mount'], 'post_mount' => []]], ['App\\Twig\\Component\\Geolocation' => 'Geolocation', 'Symfony\\UX\\Icons\\Twig\\UXIconComponent' => 'UX:Icon', 'Symfony\\UX\\Map\\Twig\\UXMapComponent' => 'UX:Map', 'Survos\\FwBundle\\Components\\MenuComponent' => 'mobile_menu']);
    }
}
