<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUxMap_RendererFactory_LeafletService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux_map.renderer_factory.leaflet' shared service.
     *
     * @return \Symfony\UX\Map\Bridge\Leaflet\Renderer\LeafletRendererFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-map/src/Renderer/AbstractRendererFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-map/src/Renderer/RendererFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-leaflet-map/src/Renderer/LeafletRendererFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-map/src/Icon/UxIconRenderer.php';

        $a = ($container->privates['stimulus.helper'] ?? self::getStimulus_HelperService($container));

        if (isset($container->privates['ux_map.renderer_factory.leaflet'])) {
            return $container->privates['ux_map.renderer_factory.leaflet'];
        }

        return $container->privates['ux_map.renderer_factory.leaflet'] = new \Symfony\UX\Map\Bridge\Leaflet\Renderer\LeafletRendererFactory($a, new \Symfony\UX\Map\Icon\UxIconRenderer(($container->privates['.ux_icons.icon_renderer'] ?? $container->load('get_UxIcons_IconRendererService'))));
    }
}
