<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUxMap_TwigRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux_map.twig_runtime' shared service.
     *
     * @return \Symfony\UX\Map\Twig\MapRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-map/src/Twig/MapRuntime.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-map/src/Renderer/RendererInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-map/src/Renderer/Renderers.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-map/src/Renderer/Renderer.php';

        return $container->privates['ux_map.twig_runtime'] = new \Symfony\UX\Map\Twig\MapRuntime((new \Symfony\UX\Map\Renderer\Renderer(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['ux_map.renderer_factory.leaflet'] ?? $container->load('getUxMap_RendererFactory_LeafletService'));
        }, 1)))->fromStrings(['default' => $container->getEnv('resolve:default::UX_MAP_DSN')]));
    }
}
