<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWindowsWidgetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpomkyLabs\PwaBundle\ServiceWorkerRule\WindowsWidgets' shared autowired service.
     *
     * @return \SpomkyLabs\PwaBundle\ServiceWorkerRule\WindowsWidgets
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/ServiceWorkerRule/ServiceWorkerRuleInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/ServiceWorkerRule/WindowsWidgets.php';

        return $container->privates['SpomkyLabs\\PwaBundle\\ServiceWorkerRule\\WindowsWidgets'] = new \SpomkyLabs\PwaBundle\ServiceWorkerRule\WindowsWidgets(($container->privates['SpomkyLabs\\PwaBundle\\Dto\\Manifest'] ?? self::getManifestService($container)), ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)));
    }
}
