<?php

namespace ContainerVro39aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkboxImportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SpomkyLabs\PwaBundle\ServiceWorkerRule\WorkboxImport' shared autowired service.
     *
     * @return \SpomkyLabs\PwaBundle\ServiceWorkerRule\WorkboxImport
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/ServiceWorkerRule/ServiceWorkerRuleInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/spomky-labs/pwa-bundle/src/ServiceWorkerRule/WorkboxImport.php';

        return $container->privates['SpomkyLabs\\PwaBundle\\ServiceWorkerRule\\WorkboxImport'] = new \SpomkyLabs\PwaBundle\ServiceWorkerRule\WorkboxImport(($container->privates['SpomkyLabs\\PwaBundle\\Dto\\ServiceWorker'] ?? self::getServiceWorkerService($container)));
    }
}
